server:
  port: 8888
  
spring:
 profiles.active: development-oracle
 
---

spring:
 profiles: development-mysql
 jpa:
    hibernate:
      naming-strategy: org.hibernate.cfg.DefaultNamingStrategy 
spring.data.jpa.repositories.enabled: true
spring.jpa:
    show-sql: true
    format-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        connection:
          pool_size:50 
logging:
  file: logFile.log
  pattern:
    console: "%d %-5level %logger : %msg%n"
    file: "%d %-5level [%thread] %logger : %msg%n"
  level:
    ROOT: INFO
    
audit.datasource:
  driverClassName: com.mysql.jdbc.Driver
  url: jdbc:mysql://127.0.0.1:3306/audit
  username: root
  password: welcome1
  accessToUnderlyingConnectionAllowed: true
  max-active: 25
  max-idle: 10
  min-idle: 10
  initial-size: 10
  validation-query: "select 1 from dual"
  test-on-borrow: true

---

spring:
 profiles: development-oracle
 jpa:
    hibernate:
      naming-strategy: org.hibernate.cfg.DefaultNamingStrategy 
spring.data.jpa.repositories.enabled: true
spring.jpa:
    show-sql: true
    format-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.Oracle10gDialect
        connection:
          pool_size:50
logging:
  file: logFile.log
  pattern:
    console: "%d %-5level %logger : %msg%n"
    file: "%d %-5level [%thread] %logger : %msg%n"
  level:
    ROOT: INFO
    
audit.datasource:
  driverClassName: oracle.jdbc.driver.OracleDriver
  url: jdbc:oracle:thin:@//localhost:1521/XE 
  username: system
  password: welcome1
  accessToUnderlyingConnectionAllowed: true
  max-active: 25
  max-idle: 10
  min-idle: 10
  initial-size: 10
  validation-query: "select 1 from dual"
  test-on-borrow: true

